#!/bin/bash

# ====================================================================================================================================
# Shell script da preguica >>>> Compila, executa, plota <<<<<

DX=0.01                       # Tamanho da discretizacao para o plot
N=100                           # Numero de funcoes de ponderacao a serem utilizadas
NUMERACAO=1                   # Numeracao dos nos utilizada || 1 = Automatica || 2 = Manual ||
# ====================================================================================================================================

echo "=========================================================================================="
echo "[!] EXECUTANDO SHELL SCRIPT DA PREGUICA                            ||____||"
echo "zZzZZZzzzZzzzzZzzzZZZZZZZZZZZzzzZZZzzZZzzz                         /     /|"
echo "                                                                  /     /"
echo "                                                                 /____ /"
echo "                                                                 |    |"
echo "=========================================================================================="

# Existe uma versao anterior do executavel, deletar arquivos da ultima execucao com clean do Makefile
if [ -f "mef" ]; then
  echo "----> [!] Deletando versoes anteriores ..."
  make clean
  echo "****************************************************************************************"
fi

# Compilar codigo fonte
echo "----> [!] Compilando codigo fonte ..."
make
echo "******************************************************************************************"

# Chamar o executavel com os parametros definidos no cabecalho desse shell
echo "----> [!] Executando programa ..."
./mef $N $DX $NUMERACAO
echo "******************************************************************************************"

# Executar script de plot do grafico
echo "----> [!] Plotando o grafico dos resultados obtidos ... "
python plot.py $N
echo "******************************************************************************************"

echo "[!] Finalizando shell script ..."
echo "=========================================================================================="

exit 0
