#!/bin/bash

# ====================================================================================================================================
# Shell script da preguica >>>> Compila, executa, plota <<<<<

NELEM=100                 # Numero de elementos
XMAX=1.0                # Tamanho do dominio
TIPOELEM=3              # 1 = Linear || 2 = Qudratico || 3 = Hermite
# ====================================================================================================================================
# Existe uma versao anterior do executavel, deletar arquivos da ultima execucao com clean do Makefile
if [ -f "mefDerivada" ]; then
  echo "----> [!] Deletando versoes anteriores ..."
  make clean
  echo "****************************************************************************************"
fi

# Compilar codigo fonte
echo "----> [!] Compilando codigo fonte ..."
make
echo "******************************************************************************************"

# Chamar o executavel com os parametros definidos no cabecalho desse shell
echo "----> [!] Executando programa ..."
./mefDerivada $NELEM $XMAX $TIPOELEM
echo "******************************************************************************************"

# Executar script de plot do grafico
echo "----> [!] Plotando o grafico dos resultados obtidos ... "
python plot.py $NELEM $TIPOELEM
echo "******************************************************************************************"

echo "[!] Finalizando shell script ..."
echo "=========================================================================================="

exit 0
