#!/bin/bash

# ====================================================================================================================================
# Shell script da preguica >>>> Compila, executa, plota <<<<<

DX=0.01                       # Tamanho da discretizacao para o plot
N=2                           # Numero de funcoes de ponderacao a serem utilizadas
NUM_METODO=1                  # Numero do metodo escolhido. ||1 = Polinomio Simples || 2 = Polinomio Lagrange || 3 = Funcoes Chapeu
# ====================================================================================================================================

echo "=========================================================================================="
echo "[!] EXECUTANDO SHELL SCRIPT DA PREGUICA                            ||____||"
echo "zZzZZZzzzZzzzzZzzzZZZZZZZZZZZzzzZZZzzZZzzz                         /     /|"
echo "                                                                  /     /"
echo "                                                                 /____ /"
echo "                                                                 |    |"
echo "=========================================================================================="

# Existe uma versao anterior do executavel, deletar arquivos da ultima execucao com clean do Makefile
if [ -f "projection_L2" ]; then
  echo "----> [!] Deletando versoes anteriores ..."
  make clean
  echo "****************************************************************************************"
fi

# Compilar codigo fonte
echo "----> [!] Compilando codigo fonte ..."
make
echo "******************************************************************************************"

# Chamar o executavel com os parametros definidos no cabecalho desse shell
echo "----> [!] Executando programa ..."
./projection_L2 $N $DX $NUM_METODO
echo "******************************************************************************************"

# Executar script de plot do grafico
echo "----> [!] Plotando o grafico dos resultados obtidos ... "
python plot.py $N $NUM_METODO
echo "******************************************************************************************"

echo "[!] Finalizando shell script ..."
echo "=========================================================================================="

exit 0
